// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.norrmann.coqui.jsf;

import ar.com.norrmann.coqui.jsf.AutomotorBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AutomotorBean_Roo_Configurable {
    
    declare @type: AutomotorBean: @Configurable;
    
}
