// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.norrmann.coqui.jsf;

import ar.com.norrmann.coqui.jsf.ClienteDebeBean;
import java.io.Serializable;

privileged aspect ClienteDebeBean_Roo_Serializable {
    
    declare parents: ClienteDebeBean implements Serializable;
    
    private static final long ClienteDebeBean.serialVersionUID = 1L;
    
}
