// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.norrmann.coqui.jsf;

import ar.com.norrmann.coqui.jsf.CompraBean;
import java.io.Serializable;

privileged aspect CompraBean_Roo_Serializable {
    
    declare parents: CompraBean implements Serializable;
    
    private static final long CompraBean.serialVersionUID = 1L;
    
}
