// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.norrmann.coqui.jsf;

import ar.com.norrmann.coqui.jsf.DetalleCompraBean;
import java.io.Serializable;

privileged aspect DetalleCompraBean_Roo_Serializable {
    
    declare parents: DetalleCompraBean implements Serializable;
    
    private static final long DetalleCompraBean.serialVersionUID = 1L;
    
}
