// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.norrmann.coqui.jsf;

import ar.com.norrmann.coqui.jsf.DetalleVentaBean;
import java.io.Serializable;

privileged aspect DetalleVentaBean_Roo_Serializable {
    
    declare parents: DetalleVentaBean implements Serializable;
    
    private static final long DetalleVentaBean.serialVersionUID = 1L;
    
}
