// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.norrmann.coqui.jsf;

import ar.com.norrmann.coqui.jsf.ItemservicioBean;
import java.io.Serializable;

privileged aspect ItemservicioBean_Roo_Serializable {
    
    declare parents: ItemservicioBean implements Serializable;
    
    private static final long ItemservicioBean.serialVersionUID = 1L;
    
}
