// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.norrmann.coqui.model;

import ar.com.norrmann.coqui.model.Modelo;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Modelo_Roo_Configurable {
    
    declare @type: Modelo: @Configurable;
    
}
