// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.norrmann.coqui.jsf.converter;

import ar.com.norrmann.coqui.jsf.converter.ProveedorConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ProveedorConverter_Roo_Configurable {
    
    declare @type: ProveedorConverter: @Configurable;
    
}
